### ISSUE TITLE
Please remove blocking "What's new" popup

### ISSUE THREAD

**Issue by sonnyp** [maoschanz/drawing#504]
Love Drawing, it's my goto tool for quickly editing screenshots <3 

## Problem

But today I was greeted with an annoying popup.

![image](https://user-images.githubusercontent.com/19673/161077551-ce3c8af9-ce9c-4520-9918-1c16256b3a9f.png)

It breaks GNOME HIG https://developer.gnome.org/hig/patterns/feedback/dialogs.html?highlight=dialog#general-guidelines 

> Never pop up a dialog window unexpectedly. They should only ever be displayed in immediate response to a deliberate user action.

And is a bad example for the rest of the platform https://gitlab.gnome.org/Teams/Circle/-/issues/114#note_1418956

## Suggestion

Let GNOME Software inform users about news.

If you must, show a toast / in-app notification.

https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.1/class.Toast.html

**Comment by maoschanz** [comment]
>a deliberate user action.

"updating the app" and "opening it" are imho two deliberate actions

>If you must, show a toast

let's have a toast to those new non-understandable, ungooglable, fancy UI elements names

>in-app notification.

i already use them for more important things, and i think it would be horrible to stack several of them like LibreOffice does

>Let GNOME Software inform users about news.

no one uses that, each time i try it it's broken, and the only time it worked for me i didn't find the release notes.

I had feedback about changes being hard to discover, so i'm afraid this annoying message dialog will have to stay here, and people will just click "no": i update it around 5 times a year, and distros don't even follow this pace, it's not THAT common to see this dialog

----

However, i agree that from the point of view of the new user who didn't know the previous version, it doesn't make a lot of sense, and in this scenario it should be removed

i could also add a "never" button to the dialog

**Comment by sonnyp** [comment]
> "updating the app" and "opening it" are imho two deliberate actions

GNOME Software automatically update apps by default.

Opening the app is a deliberate action to use it, not see what's new.

Regardless of my interpretation or the wording in HIG - this "What's new" popup pattern is discouraged in GNOME.

> i think it would be horrible to stack several of them like LibreOffice does

FYI - Adw toasts don't stack but agree it's not a good solution either.

> i update it around 5 times a year, and distros don't even follow this pace, it's not THAT common to see this dialog

I use the flatpak, imagine every app did this after an update.

> I had feedback about changes being hard to discover, 

What about a "What's new" menu item instead? That way, users can consult it any time and come back to it if they need / forgot something.

**Comment by maoschanz** [comment]
>I encourage you give it a try

that appstore never works, it takes 900MB of RAM in the background, it only exists on 1 DE while the app works with many, and what you describe sounds like the most inefficient way imaginable to make people discover what's new

>can you clarify why it is so important that Drawing must inform users of changes?

the concept of an image editor is that, depending on the selected options, you can interact in hundreds of ways with the canvas. Yet there is only 3 mouse buttons, a wheel, and 3 keyboard modifiers: in order to do anything you **have to** know what the tools and their options are and do. This process mainly relies on:
- familiarity with common icons, which is kinda weak; 
- pertinent and recognizable labels, but i'm not a native english speaker and i don't use any app in that language. Contributions on this topic are welcome;
- and trial & error, which isn't very user-friendly, and is time consuming for everyone given the number of possible interactions with the canvas.

there were very specific complains like the reddit one, but when i discussed with users of the first versions, they often told more broadly how they didn't know this or that was possible, what that UI element would do, etc... Although most of it was written in the help manual! People don't click on the "help" menu item, they assume it'll be a link to an online labyrinth, or short useless obvious general advice to tell boomers how to right-click

So i push my explanations in the user's throat as much as possible, and i prefer a single complain about having to click "no" a few times per year, rather than dozens of people who never knew the feature they needed daily was here since a 6 months old update they didn't notice.

Ok, it could be less disruptive, but in the current state of the app, that's a very unimportant problem imho

**Comment by maoschanz** [comment]
maybe greeting users with a blocking modal dialog when they open a new software is different from the guideline you showed me, and it might in fact be an accepted pattern:

- Glade kinda does it, and it's quite long though it's not 100% blocking IIRC
- GTranslator does it to force us to configure the app
- GNOME itself has a dedicated "tour" app, making use of the Yelp app to show help pages, kinda like me, for GNOME Shell and the core apps

Now the question becomes "is a new version of an app the same as a new app?", and the answer i implemented is:

- show this dialog when it's a major update, and not show it anymore when it's a minor one
- write in the dialog that the info will stay available in the help manual
- remove the "later" option, because i believe websites' implementation of GDRP has conditioned us to treat "later" as "no", which isn't the case at all here
- pre-select the "no" button, instead of "yes", because it's really a pain in the ass to click yes by accident and it takes 5 seconds to show up
- use a more adequate message in the dialog when people are using the app for the first time

So far, in 3 years, there has been 5 major updates in total, it's not that much, so i think the issue is fixed enough, i'll close it

**Comment by sonnyp** [comment]
There are valid use cases for opening a dialog on app launch. "What's new" isn't one. Spamming user neither.

Please don't use other apps doing something unrelated to justify you wanting to spam users.

This is still an issue IMHO but worse, will continue to serve as a bad example for the GNOME ecosystem.

See https://gitlab.gnome.org/Teams/Circle/-/issues/114#note_1421567

> I originally took this idea from [Drawing](https://apps.gnome.org/app/com.github.maoschanz.drawing/) which is part of Circle, but in hindsight it's intrusive and a bit annoying

A dozen years ago, every app and website would open useless popups and banners all the time, we finally managed to kill this pattern and I do not wish to see it come back.

As a reminder

https://gitlab.gnome.org/Teams/Circle/-/blob/master/README.md#who-can-apply

> Applications should:

> Have a well-designed UI which generally follows GNOME conventions

Here is to hopping GNOME Circle doesn't need to start policing member applications.

**Comment by sonnyp** [comment]
What that said – thank you for putting effort into improving the situation.

If you ever wish to reconsider – I invite you to ask the wider community how to solve https://github.com/maoschanz/drawing/issues/504#issuecomment-1085147517 

Cheers

**Comment by maoschanz** [comment]
> every [...] website would open useless popups and banners all the time, we finally managed to kill this pattern

did we?

i see what you mean, but helping the user to understand how their app has evolved isn't the same as asking to rate the app or enable notifications or accept cookies or subscribe to a newsletter or whatnot, which is insanely common on many websites, windows apps, or android apps

the closest thing from 12 years ago you could bring up is Clippy, and it was annoying because it was dumb as hell, and you saw it far more than 5 times in 3 years

>I invite you to ask the wider community how to solve https://github.com/maoschanz/drawing/issues/504#issuecomment-1085147517

i forgot to tell it but i already 100% agree with the concept of the badge, my favorite way to present release notes is how Firefox does it (and i think it's kinda what you meant by this suggestion?), but currently with just GTK3 this alternative seems very complex and unrealistic to implement

i hope GTK4 has widgets to that, or something similar, but i haven't started the port yet so i don't know the exact possibilities. Meanwhile just "spamming" as little as possible is fine: i mean, there will be a major "1.2.0", and then it'll be the 2.0.0 in GTK4, so people will see it only once more

**Comment by maoschanz** [comment]
of course if you have a realistic idea of how to implement a badge in GTK3, pull requests are welcome

(i don't care about supporting this with alternative layouts, just the GNOME one is enough)
